#include "afr-vexu-lib/base-commandable/motor_commandable.h"
#include "afr-vexu-lib/base-commandable/adi_analog_commandable.h"
#include "afr-vexu-lib/base-readable/adi_encoder_readable.h"
#include "afr-vexu-lib/base-readable/motor_encoder_readable.h"
#include "afr-vexu-lib/base-readable/adi_analog_readable.h"
#include "afr-vexu-lib/base-readable/adi_digital_readable.h"